name: Parallel testing 
on: push
jobs:
  add-to-cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Add To Cart Run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:browser
       
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Mochaawesome HTML Report - Add To Cart
            path: cypress/reports/html     

  register-flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      
      - name: Register Flow Run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerFlow

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
              name: Mochaawesome HTML Report - Register Flow
              path: cypress/reports/html     
         
         
  
          
